<table>
    <thead>
    <tr>
        <th>No</th>
        <th>Nama</th>
        <th>NPA</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>2</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>3</td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>