version: '3.8'

services:
  web:
    container_name: ${CONTAINER_APP_PROD}
    image: ${REPOSITORY_ECR_URL}:${TAG_ANA}
    volumes:
      - ./docker-data/evoting/logs:/var/www/evoting/storage/logs:rw
      - ./.env:/var/www/evoting/.env
    environment:
      - DB_CONNECTION=${PROD_MYSQL_CONNECTION}
      - DB_HOST=${PROD_MYSQL_HOST}
      - DB_PORT=${PROD_MYSQL_PORT}
      - DB_DATABASE=${PROD_MYSQL_DATABASE}
      - DB_USERNAME=${PROD_MYSQL_USER}
      - DB_PASSWORD=${PROD_MYSQL_PASSWORD}
      - APP_ENV=${APP_ENV}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - MAIL_DRIVER=${PROD_MAIL_DRIVER}
      - MAIL_HOST=${PROD_MAIL_HOST}
      - MAIL_PORT=${PROD_MAIL_PORT}
      - MAIL_USERNAME=${PROD_MAIL_USERNAME}
      - MAIL_PASSWORD=${PROD_MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${PROD_MAIL_ENCRYPTION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET_PROD}
    ports:
      - ${PROD_PORT_MAPPING}:8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      PMA_HOST: ${PROD_MYSQL_HOST}
    ports:
      - ${PROD_PORT_MAPPING_PHPMYADMIN}:80


