version: '3.8'
services:
  db:
    container_name: evoting-db
    image: mysql:8.0
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    restart: always
    volumes:
      - ./evoting-database/:/var/lib/mysql
      - ./mysql/remote.conf:/etc/mysql/conf.d/remote.conf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
  web:
    container_name: evoting-app
    image: ${REPOSITORY_ECR_URL}:${TAG_EVOTING}
    volumes:
      - ./docker-data/evoting-new/logs:/var/www/evoting/storage/logs:rw
      - ./.env:/var/www/evoting/.env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    ports:
      - 80:8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: ${PHPMYADMIN_URL}/evoting-pma/
    depends_on:
      - db
